"""empty message

Revision ID: 26518ff59844
Revises: 7b6d737a8b8d
Create Date: 2024-04-28 11:47:06.726470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26518ff59844'
down_revision = '7b6d737a8b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_confirmation', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_confirmation')
    # ### end Alembic commands ###
